name: Bug Report
description: Create a report to help us improve
title: '[Bug]: '
labels: ["bug", "triage"]

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
      - Linux
      - Windows
      - MacOS
  - type: textarea
    id: logs
    attributes:
      label: The script
      description: Please copy and paste the program with `cat /usr/local/bin/mktouch`. This will be automatically formatted into code, so no need for backticks.
      render: shell
