name: mktouch

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'main'
      - 'releases/**'

jobs:
  mktouch:
    name: Run mktouch
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run valid script
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          ./mktouch.sh ./temp/{1,2,3,4} - index.sh

          [ ! -f "./temp/1/index.sh" ] && { echo "./temp/1/index.sh does not exist"; exit 1; } || echo "./temp/1/index.sh does exist"
          [ ! -f "./temp/2/index.sh" ] && { echo "./temp/2/index.sh does not exist"; exit 1; } || echo "./temp/2/index.sh does exist"
          [ ! -f "./temp/3/index.sh" ] && { echo "./temp/3/index.sh does not exist"; exit 1; } || echo "./temp/3/index.sh does exist"
          [ ! -f "./temp/4/index.sh" ] && { echo "./temp/4/index.sh does not exist"; exit 1; } || echo "./temp/4/index.sh does exist"
        shell: bash
      - name: Run invalid script
        run: |
          ./mktouch.sh ./temp/dir || echo "Failed correctly with invalid arg length"

          ./mktouch.sh - index.sh || echo "Failed correctly with no dir"

          ./mktouch.sh ./temp/dir - || echo "Failed correctly with no files"
        shell: bash
